### ISSUE TITLE
Add morph simplifier?

### ISSUE THREAD

**Issue by arnaudon** [BlueBrain/morph-tool#110]
We could consider adding this: 

https://github.com/mgeplf/NeuroM/commit/27caf638a05853037a8adee480f54004d827d582#diff-84b775029ec507bf4bb7dee809be38b8cf3f4729553c2ed9bcfb6581b6b9bcb0R62

near the resampling code?

**Comment by eleftherioszisis** [comment]
Sure, I'll add it.

**Comment by mgeplf** [comment]
Hmm, I might actually have rewritten it in MorphIO at some point, let me check.

**Comment by mgeplf** [comment]
ahem, almost a year ago:
https://github.com/BlueBrain/morph-tool/tree/line_simplification

**Comment by mgeplf** [comment]
I don't remember how good/bad #111 was, but it's a starting point.

**Comment by arnaudon** [comment]
Don't get to triggered by this haha, it is not urgent at all i think.

**Comment by eleftherioszisis** [comment]
@arnaudon , may I close this? You can open a new ticket if you want a different behavior with simplify.
