### ISSUE TITLE
multiple axon grafting exception

### ISSUE THREAD

**Issue by arnaudon** [BlueBrain/morph-tool#15]
Just got this thrown at me on some cells with apparently 2 axons:

https://github.com/BlueBrain/morph-tool/blob/master/morph_tool/graft.py#L31

it seems to work with any number of axons, as it returns [0], why raising an exception, and not something like L.warning('more than one axon, be careful!') ?

**Comment by wizmer** [comment]
The question is how do you choose which axon to replace if you have many ?

**Comment by arnaudon** [comment]
It takes the first one in the list, which is reasonable I think. Afaik, there should not be several axons, but if there is taking the first one should work, with a warning of course!

**Comment by arnaudon** [comment]
solved here: https://github.com/BlueBrain/morph-tool/pull/35#discussion_r522823537
